version: '3'
services:

    market-nginx:
        build:
            context: ./market/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./market:/app
        depends_on:
            - market-php-fpm
            - roundcube
        ports:
            - "80:80"
            - "443:443"

    market-php-fpm:
        build:
            context: ./market/docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./market:/app
        depends_on:
            - market-mail-postgres
            - market-postgres
            - market-redis
            - market-queue-redis
            - storage
            - centrifugo
            - roundcube

    market-php-cli:
        build:
            context: ./market/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./market:/app
            - composer:/root/.composer/cache
        depends_on:
            - market-mail-postgres
            - market-postgres
            - market-redis
            - market-queue-redis
            - storage
            - centrifugo
            - roundcube

    market-queue-worker:
        build:
            context: ./market/docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./market:/app
            - composer:/root/.composer/cache
        depends_on:
            - market-mail-postgres
            - market-postgres
            - market-redis
            - market-queue-redis
            - storage
            - centrifugo
            - roundcube
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && php bin/console messenger:consume async -vv"

    market-node-watch:
        image: node:12.7-alpine
        volumes:
            - ./market:/app
        working_dir: /app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && npm run watch"

    market-node:
        image: node:12.7-alpine
        volumes:
            - ./market:/app
        working_dir: /app

    market-postgres:
        image: postgres:11.2-alpine
        volumes:
            - market-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: marketdb
        ports:
            - "54321:5432"

    market-mail-postgres:
        image: postgres:11.2-alpine
        volumes:
            - market-mail-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: roundcube
            POSTGRES_PASSWORD: secretas
            POSTGRES_DB: roundcube
        ports:
            - "54322:5433"

    market-redis:
        image: redis:5.0-alpine
        volumes:
            - market-redis:/data
        command:
            - 'redis-server'
            - '--databases 2'
            - '--save 900 1'
            - '--save 300 10'
            - '--save 60 10000'
            - '--requirepass secret'

    market-queue-redis:
        image: redis:5.0-alpine
        volumes:
            - market-queue-redis:/data

    storage:
        build:
            context: ./storage/docker/development
            dockerfile: nginx.docker
        volumes:
            - ./storage:/app
        ports:
            - "8081:80"

    storage-ftp:
        image: stilliard/pure-ftpd
        environment:
            FTP_USER_NAME: app
            FTP_USER_PASS: secret
            FTP_USER_HOME: /app
        volumes:
            - ./storage/public:/app

    #    mailer:
    #        image: mailhog/mailhog
    #        ports:
    #            - "8082:8025"

    mailserver:
        image: tvial/docker-mailserver:latest
        hostname: '${HOSTNAME:-mail}'
        domainname: '${DOMAINNAME:-arsku.com}'
        container_name: '${CONTAINER_NAME:-mail}'
        restart: always
        ports:
            # receiving email from other mailservers
            - "25:25"
            # SSL & TLS Client email submission (SMTP)
            - "465:465"
            - "587:587"
            # StartTLS & TLS/SSL IMAP client
            - "143:143"
            - "993:993"
            # POP3 & TLS/SSL POP3 client
            - "110:110"
            - "995:995"
            # Manage Sieve port
            - "4190:4190"
        volumes:
            - maildata:/var/mail
            - mailstate:/var/mail-state
            - maillogs:/var/log/mail
            - ./config/:/tmp/docker-mailserver/
        environment:
            - ENABLE_SPAMASSASSIN=1
            - ENABLE_CLAMAV=1
            - ENABLE_FAIL2BAN=1
            - ENABLE_POSTGREY=1
            - ONE_DIR=1
            - DMS_DEBUG=0

        cap_add:
            - NET_ADMIN
            - SYS_PTRACE


    centrifugo:
        image: centrifugo/centrifugo:v2.2
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        environment:
            CENTRIFUGO_SECRET: secret
            CENTRIFUGO_API_KEY: secret
        volumes:
            - ./centrifugo/docker/development/centrifugo:/centrifugo
        ports:
            - "8083:8000"
        command: centrifugo --admin --admin_insecure

    market-adminer:
        image: adminer
        restart: always
        ports:
            - "8085:8080"

    market-pgadmin:
        image: dpage/pgadmin4:latest
        depends_on:
            - market-postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: user@domain.com
            PGADMIN_DEFAULT_PASSWORD: secretas
        volumes:
            - market-pgadmin-data:/var/lib/pgadmin
        ports:
            - "8086:80"

    roundcube:
        restart: unless-stopped
        image: 'roundcube/roundcubemail:${ROUNDCUBE_VERSION:-latest}'
        depends_on:
            - market-mail-postgres
            - mailserver
        environment:
            ROUNDCUBEMAIL_DEFAULT_HOST: '${IMAP_SERVER:-mail}'
            ROUNDCUBEMAIL_DEFAULT_PORT: '${IMAP_PORT:-143}'
            ROUNDCUBEMAIL_SMTP_AUTH_TYPE: '${SMTP_AUTH_TYPE:-PLAIN}'
            ROUNDCUBEMAIL_SMTP_SERVER: '${SMTP_SERVER:-tls://mail}'
            ROUNDCUBEMAIL_SMTP_PORT: '${SMTP_PORT:-587}'
            ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: '20M'
            ROUNDCUBEMAIL_DB_TYPE: 'pgsql'
            ROUNDCUBEMAIL_DB_HOST: 'market-mail-postgres'
            ROUNDCUBEMAIL_DB_USER: '${PGSQL_USER:-roundcube}'
            ROUNDCUBEMAIL_DB_PASSWORD: '${PGSQL_PASSWORD:-secretas}'
            ROUNDCUBEMAIL_DB_NAME: 'roundcube'
        ports:
            - '9000:80'

volumes:
    market-mail-postgres:
    market-postgres:
    market-redis:
    market-queue-redis:
    market-pgadmin-data:
    mysql-data:
    maildata:
    mailstate:
    maillogs:
    composer:
